### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by cappittall** [firebase/friendlychat#105]
At your page : 
https://codelabs.developers.google.com/codelabs/firebase-web/#8    and,
https://codelabs.developers.google.com/codelabs/firebase-web/#11  and 
https://codelabs.developers.google.com/codelabs/firebase-web/#12

At firebase.json file description says ;  "storage.rules"  
This is giving " Error: unexpected error has occurred message at firebase deploy" 
I think correct way must be "storage-rules.json"  

Regards,
Hakan

**Comment by nicolasgarnier** [comment]
Hey @cappittall,

It's really `storage.rules`, that's how I prefer to call that file because it's not JSON. See:

https://github.com/firebase/friendlychat/blob/master/web/storage.rules

The error might come from something else. Have you checked the deploy.log file after the error happens?

**Comment by cappittall** [comment]
Sorry, you are right. I did mistake.

**Comment by cappittall** [comment]
But its not working proper at IE11 or Microsoft Edge

**Comment by nicolasgarnier** [comment]
Can you tell me what's not working on IE ? IF it's a CSS/UI bug can you copy paste a screenshot?
