### ISSUE TITLE
Sign-in Failed - Android

### ISSUE THREAD

**Issue by CreaRo** [firebase/friendlychat#11]
While trying to sign-in, I keep getting the following error.
`E/SignInActivity: Google Sign In failed. Status{statusCode=unknown status code: 12501, resolution=null}, null`
I suspect it's the GoogleSignInOptions `requestIdToken()` method causing the issue. I changed the string passed as the `default_web_client_id` to the credentials of server key auto generated in Google APIs credentials. That doesn't seem to work either.

Am I missing something, or doing something wrong?

**Comment by nicolasgarnier** [comment]
@gkaldevrel could you have a look?

**Comment by gkaldevrel** [comment]
@kroikie who worked on this component.

**Comment by niiapa** [comment]
Same error. Any headway?

**Comment by slotbite** [comment]
Well finally login , make a new project, after get the sha1 code in Gradle->Android-start->Tasks->singningReports, put the new google-services.json on src folder and uninstall app ..... Run the project! and voilà , happy coding!

**Comment by kroikie** [comment]
@CreaRo is this still an issue for you. If so I would double check that you are using the correct SHA1 and package name for your project, also be sure that you are including the correct google-services.json file.

**Comment by CreaRo** [comment]
I'll try again in a couple days and update.

**Comment by CreaRo** [comment]
I completely forgot to close this! Yes, it worked, thanks a lot @slotbite, @niiapa :+1:

**Comment by karol-202** [comment]
I have got the same issue: Google Sign In failed. I've tried setting SHA1 from signingReport in Firebase Console and updating google.services.json file but app still doesn't work.

**Comment by CreaRo** [comment]
Are you getting 12501 as the error code? If yes, and you've made sure the SHA1 keys, package names match, then that's odd. Could you double check everything's alright? If you haven't already, [this](http://bhardwajrish.blogspot.in/2016/09/firebase-auth-debug-vs-release.html) blogpost might help.

**Comment by karol-202** [comment]
The blogpost you've written helped me a lot. I've generated new keystore and now it works! Thank you.

**Comment by jburgoyn** [comment]
I am confused about how the completed chat sample code works just fine without having to do any of the above? I downloaded the completed sample code, could run on both device and emulator and be able to log in with google just fine. And obviously the sha1 in the firebase project wouldn't match my computers sha1, so how does that work when it doesn't work when I follow these steps implementing into an existing project I have.

I was able to get it to work on my emulator by adding my sha1 to the fire base console project, however when I run on device I still get the Google signing failed error.

**Comment by lumleon** [comment]
I am also so confusing to run the app at Samsung S4 that at the beginning  "class for com.google.firebase.auth not found." and end up "sign-in" not successful.

I tried to download the JSON file again but it still not work.

log:

12-09 23:28:35.697 5108-5108/? D/ResourcesManager: creating new AssetManager and set to /data/app/com.google.firebase.codelab.friendlychat-1/base.apk
12-09 23:28:35.727 5108-5108/? I/InstantRun: Instant Run Runtime started. Android package is com.google.firebase.codelab.friendlychat, real application class is null.
12-09 23:28:37.849 5108-5108/com.google.firebase.codelab.friendlychat W/art: Verification of void com.google.firebase.FirebaseApp.<clinit>() took 101.837ms
12-09 23:28:38.830 5108-5225/com.google.firebase.codelab.friendlychat W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
12-09 23:28:38.900 5108-5225/com.google.firebase.codelab.friendlychat W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.

...

 "12-09 23:29:19.069 5108-5108/com.google.firebase.codelab.friendlychat E/SignInActivity: Google Sign In failed."

**Comment by Divala** [comment]
Update your Google play services to 9.4.0 or above

**Comment by lumleon** [comment]
Hi, I had already update the the latest Google Play  Services to Rev 38 and the Repository to Rev 40 . The problem is the same.

**Comment by Divala** [comment]
Okay, have you set authentication methods in firebase console?

**Comment by lumleon** [comment]
yes, the Google sign-in method was enabled

**Comment by lukiee555** [comment]
pkg: /data/local/tmp/com.google.firebase.udacity.friendlychat
Failure [INSTALL_FAILED_MEDIA_UNAVAILABLE]
