### ISSUE TITLE
ios Failed to fetch default token Error Domain

### ISSUE THREAD

**Issue by anks62** [firebase/friendlychat#116]
Hi,
I used developer certificate and developer provisioning profile. friendlychat also work fine in simulator but when I run project in iPad with same login credential, node which i used in simulator means same project i run in iPad I can not get any data in iPad. 
These all things are perfect working in simulator. I used Two simulators iPhone 5s and iPhone 6s Plus for testing.

I send message iPhone 6s Plus and I get data on iPhone 5s Simulator. vice versa. I get data entry in Realtime Database. 

I send message through iPad I can not get any data entry in Realtime Database.      

I get Error on iPad -> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "(null)"

I used GoogleService-Info.plist which I get from my account. 

anyone help me

**Comment by iulukaya** [comment]
Is this still valid?
