### ISSUE TITLE
FriendlyMessage does not have getId/setId

### ISSUE THREAD

**Issue by samtstern** [firebase/friendlychat#119]
In this step (and others) the getter/setter for ID on `FriendlyMessage` are referenced:
https://codelabs.developers.google.com/codelabs/firebase-android/#8

But nowhere in the codelab does it have the developer add them, and the android-start code does not contain those methods or that field.

**Comment by zayna-shahzad** [comment]
Fixed with https://github.com/firebase/friendlychat/pull/115 being merged in. Closing this! Thanks, Sam! :)
