### ISSUE TITLE
Sign-in Failed - Android

### ISSUE THREAD

**Issue by ridhwandaud** [firebase/friendlychat#12]
#I cannot sign in again after sign out , got this error in logcat

signInWithCredential:onComplete:false
signInWithCredential com.google.firebase.FirebaseException: An internal error has occured. [ Invalid id_token in IdP response: ...]
at com.google.android.gms.internal.zzacq.zzbN(Unknown Source)
at com.google.android.gms.internal.zzacn$zzg.zza(Unknown Source)
at com.google.android.gms.internal.zzacy.zzbO(Unknown Source)
at com.google.android.gms.internal.zzacy$zza.onFailure(Unknown Source)
at com.google.android.gms.internal.zzact$zza.onTransact(Unknown Source)
at android.os.Binder.execTransact(Binder.java:453)

Using emulator to get this error, is that the cause of this?

**Comment by nicolasgarnier** [comment]
@gkaldevrel could you have a look?

**Comment by gkaldevrel** [comment]
@kroikie who worked on this component.

**Comment by kroikie** [comment]
Hi @ridhwandaud to be clear you are able to sign-in initially but when you sign out and you try to sign in again you are getting this error?

**Comment by ridhwandaud** [comment]
@kroikie yes I can login initially but cannot second times , but I think can closed this issue because the app can now run in emulator after i reboot the emulator.

**Comment by artavazdghazaryan** [comment]
Encountered the same error in emulator. Was very confused, because no changes were done and the code worked before. Restarted the emulator and SignIn worked as magic.

**Comment by mohaemen** [comment]
These comments saved my day!
