### ISSUE TITLE
MESSAGE_URL undefined

### ISSUE THREAD

**Issue by samtstern** [firebase/friendlychat#120]
Looks like in this commit:
https://github.com/firebase/friendlychat/commit/7fc5cae5cfe2c6205398eef14abd7b622c6967ce

We added `MESSAGE_URL` to the final MainActivity but it's not in the starter one and I don't see anywhere in the codelab when we should add it.  I'd expect it to be in https://codelabs.developers.google.com/codelabs/firebase-android/#8

**Comment by zayna-shahzad** [comment]
Fixed in https://github.com/firebase/friendlychat/pull/115, but need it to be reviewed and merged. Mind taking a look @samtstern So i can get that in? :)

**Comment by zayna-shahzad** [comment]
Merged :) Closing this.
