### ISSUE TITLE
FriendlyMessage does not have getText() function in starter code

### ISSUE THREAD

**Issue by dektar** [firebase/friendlychat#121]
FriendlyMessage.java from the android-start is missing the getText() function:

public String getText() {
  return text;
}

It is easy enough to add, but does mean that the build fails at https://codelabs.developers.google.com/codelabs/firebase-android/#5 after copy-pasting code into MainActivity.java.

**Comment by zayna-shahzad** [comment]
Don't know why I accidentally removed this... must have been half asleep that day or something :/ Added back. Thank you!
