### ISSUE TITLE
Firebase analytics tutorial missing Manifest permissions

### ISSUE THREAD

**Issue by dektar** [firebase/friendlychat#123]
On this page: https://codelabs.developers.google.com/codelabs/firebase-android/#12

The codelab has the user initialize Firebase analytics as follows:
mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);

This creates a build error because the Manifest needs two additional permissions: WAKE_LOCK and ACCESS_NETWORK_STATE. This is easy for the user to resolve, but it might be nice if the tutorial first had the user add these additional permissions to the manifest, and maybe explained why they are necessary.

**Comment by samtstern** [comment]
@dektar the permissions required should be merged in via gradle, you should not have to add manual permissions to make any Firebase products work.

Did you change the build.gradle file?  How are you building the app?

**Comment by dektar** [comment]
Ahh, thanks, build.gradle was missing compile 'com.google.firebase:firebase-analytics:10.0.0'. When I add this, I can remove my two new permissions from the manifest.
