### ISSUE TITLE
11. Send images issue

### ISSUE THREAD

**Issue by nikolaspapirniywork** [firebase/friendlychat#13]
There is a bug in a code

`
// Sets the URL of the given img element with the URL of the image stored in Firebase Storage.
FriendlyChat.prototype.setImageUrl = function(imageUri, imgElement) {
  // If the image is a Firebase Storage URI we fetch the URL.
  if (imageUri.startsWith('gs://')) {
    imgElement.src = FriendlyChat.LOADING_IMAGE; // Display a loading image first.
    this.storage.refFromURL(imageStorageUri).getMetadata().then(function(metadata) {
      imgElement.src = metadata.downloadURLs[0];
    });
  } else {
    imgElement.src = imageUri;
  }
};
`
In line 
`this.storage.refFromURL(imageStorageUri).getMetadata().then(function(metadata) {`
imageStorageUri should be replaced with imageUri

**Comment by nicolasgarnier** [comment]
Sorry about that and thanks for the report! I've fixed it now and the fix will be published very soon.
