### ISSUE TITLE
Typing.....

### ISSUE THREAD

**Issue by GauravCreed** [firebase/friendlychat#135]
Hi @proppy 

i am implementing a Firebase chat on android, i want to display like whatsApp in my app like **USER is Typing......** , in my app chat is one to one not multiple user, is it possible in that ...?  then please help me.

Thanks. (_)

**Comment by morganchen12** [comment]
This question is better suited for StackOverflow.

Firebase Database does update in real time, so you can create a child of your database that's responsible for recording who's typing at any given moment. On the client, write to the database node whenever someone starts or stops typing.

```
"typing": {
    "user1": true,
    "user2": true,
}
```

Then just subscribe to changes at that node, download all the keys, and display them in your UI.
