### ISSUE TITLE
Sign-in button does not appear after completing step 1-7

### ISSUE THREAD

**Issue by ashleyliu31** [firebase/friendlychat#138]
DELETED

**Comment by EmersonFJ** [comment]
What was the ultimate solution here?

Thank you very much!

**Comment by ashleyliu31** [comment]
Try finding the button in the HTML code and delete "hidden" in "hidden ID" let me know if that works for u!

**Comment by nicolasgarnier** [comment]
Can you guys please use the issue #134 for this issue lease. Feel free to chime in there :)
