### ISSUE TITLE
"Did you find a mistake?" overlaps list of of lessons

### ISSUE THREAD

**Issue by ViliusKraujutis** [firebase/friendlychat#145]
<img width="243" alt="screen shot 2017-01-29 at 12 09 14" src="https://cloud.githubusercontent.com/assets/1859636/22403314/f477c16a-e61b-11e6-8093-dac472ad45f0.png">

Maybe some padding to the bottom would help?

**Comment by kroikie** [comment]
Thanks for pointing this out. We are looking into it.
