### ISSUE TITLE
com.google.firebase.codelab.friendlychat W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.

### ISSUE THREAD

**Issue by ashokbugude** [firebase/friendlychat#149]
I have imported the 'android-start' sample code , After step 6 in Android
When I click on sign in , I get below error in android terminal and sign in fails with error "E/SignInActivity: Google Sign In failed"
02-02 16:17:55.172 14103-14136/com.google.firebase.codelab.friendlychat W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.

**Comment by kroikie** [comment]
@ashokbugude that error often indicates that you may be using an old version of Google Play Services on the device. Update it and the auth module should be found.
