### ISSUE TITLE
Undesired overflow-x scrolling for #messages div (not present in tutorial screenshots)

### ISSUE THREAD

**Issue by smrubin** [firebase/friendlychat#15]
The CSS `.message-container .name { width: 100%; padding-left: 40px; }` is causing an undesired x-scroll on the messages list; due to box-sizing adding the 40px padding to the total width.

Could modify the rule above or add `box-sixing: border-box`.

**Comment by nicolasgarnier** [comment]
Fixed! Thanks for the report!
