### ISSUE TITLE
Misspelling in 11. Track User Flows

### ISSUE THREAD

**Issue by huckphin** [firebase/friendlychat#150]
URL: https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#10

Text: "Firebase Analytics provides a way for you to understand the way users move through your application, _where the succeed and where they get stuck_ and turn back. It can also be used to understand the most used parts of your application."

Should be: "Firebase Analytics provides a way for you to understand the way users move through your application, _where they succeed and where they get stuck_ and turn back. It can also be used to understand the most used parts of your application."

**Comment by nicolasgarnier** [comment]
This one is for you @iulukaya !

**Comment by iulukaya** [comment]
Fixed, thanks!
