### ISSUE TITLE
Web - Messages doesn't load and can't send messages

### ISSUE THREAD

**Issue by cassaregh** [firebase/friendlychat#151]
Obviously I followed the tutorial up to step 7 which I don't have problem encountered. I commented the other thread here about the "Sign in with google" doesn't appear in localhost but when I tried to deploy it the said button appear. I decided to continue the tutorial, I will just deploy the project after some changes. After finishing the step where to load messages, I deployed the project without any problem. I went to the domain, I signed in, but the messages doesn't appear. I tried to skip it and proceed to sending messages but still no luck. I keep on deploying the project since I can't use it in localhost because of the "Sign in with google" problem. What could be the cause of this problem? Any help would be appreciated. Thanks

**Comment by nicolasgarnier** [comment]
hey @cassaregh,

Could you please post the public URL of your app (since you've deployed it) so we could have a look?  Otherwise, at any moment you can try to deploy the finished app which is in the `/web` folder and compare your code with the one in `/web`.

**Comment by nicolasgarnier** [comment]
Closing since this has been awhile but please re-open if you still need assistance.
