### ISSUE TITLE
After connecting custom domain, Google sign-in not working through custom domain

### ISSUE THREAD

**Issue by MattnetLLC** [firebase/friendlychat#152]
When visiting web app through normal firebase link, it works fine, but not through the custom domain connection.  Also, neither one is showing the user pic next to username?

https://matterialx.net/

Thanks!

**Comment by MattnetLLC** [comment]
1/2 Solved...needed to add custom domain to oauth redirect list in firebase console.  Works fine now.  Still no user pic displaying though...

**Comment by nicolasgarnier** [comment]
I just posted a message and I see my pic :)

<img width="534" alt="screen shot 2017-02-05 at 08 05 13" src="https://cloud.githubusercontent.com/assets/3766663/22624351/e0ea0f32-eb79-11e6-9501-284d57bebfa7.png">

The first three messages are just test anonymous messages (so there is no user pics per say). Seems to me this is working?

**Comment by MattnetLLC** [comment]
Thanks for your reply.  I was actually referring to the user pic located to right of username which is to the right of signout in the header.  Only my username shows up there, no user pic.
Also, when I type a message, and click the send button, nothing happens....curious how it worked for you?  Could my database rules be excluding me somehow?

**Comment by nicolasgarnier** [comment]
It seems that in your code you have commented out those two lines:

https://github.com/firebase/friendlychat/blob/master/web-start/scripts/main.js#L130-L131

If you put them back the signed-in user will be displayed on the top right.

Concerning your pic not showing in the messages I'm investigating...

**Comment by nicolasgarnier** [comment]
Hey Matt, I'm not sure why your profile is not showing up). Can you tell me what account you've used to sign-in your app? i.e. does it have an attached Google+ profile? or is it a GSuite account by any chance?

**Comment by nicolasgarnier** [comment]
I'm closing this but feel free to reply if you still need help.
