### ISSUE TITLE
Web-start Step 8 references missing initial_messages.json file

### ISSUE THREAD

**Issue by engelke** [firebase/friendlychat#154]
The tutorial says to "Browse to the initial_messages.json file in the starter directory" and import it, but there is no such file.

**Comment by nicolasgarnier** [comment]
@engelke Thanks for the report. FYI the fie is at the root of the repo:

https://github.com/firebase/friendlychat/blob/master/initial_messages.json

I've changed the wording in the instructions to:

"
Browse to the [initial_messages.json](https://github.com/firebase/friendlychat/blob/master/initial_messages.json
) file at the root of the repository
"

We'll see this the next time we re-publish the codelab.
