### ISSUE TITLE
Starter App not running

### ISSUE THREAD

**Issue by ranesr** [firebase/friendlychat#156]
Tutorial [#3 - Build the starter app](https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#2)

I followed the first three steps.
After that when I click the **RUN** button, I get the following error:

`'You must specify |clientID| for |GIDSignIn|'`

EDIT:
If I write this line in `AppDelegate.swift`, it runs-

`GIDSignIn.sharedInstance().clientID = FIRApp.defaultApp()?.options.clientID`

**Comment by iulukaya** [comment]
Fixed.

**Comment by Maryom** [comment]
O got the same error:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'You must specify |clientID| for |GIDSignIn|'`

Any help?!

**Comment by iulukaya** [comment]
I fixed the issue 8 days ago, can you make sure you have the latest version of the repo?

**Comment by Maryom** [comment]
@iulukaya Yes I'm using the latest version and still same issue. It's really weird

**Comment by iulukaya** [comment]
If you follow the steps, it'll tell you

"write this line in AppDelegate.swift, it runs-

GIDSignIn.sharedInstance().clientID = FIRApp.defaultApp()?.options.clientID"

in the meantime I'll test again to make sure it builds out of the box.

**Comment by Maryom** [comment]
Yes I wrote kindly check the image below. Also, I tried to write the client ID manually and still same error!

<img width="622" alt="screen shot 2017-03-23 at 9 29 25 pm" src="https://cloud.githubusercontent.com/assets/3218401/24263981/ee0dac0e-100f-11e7-8f41-4e907858e161.png">

**Comment by ranesr** [comment]
@Maryom @iulukaya I downloaded the latest version and followed first 3 tutorials and can verify that the starter app runs without adding any new line of code.

**Comment by Maryom** [comment]
@ranser Did you run it after [Identify Users](https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#4) step?

**Comment by ranesr** [comment]
@Maryom Yes. I actually completed [Step 6 - Activate Realtime Database](https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#5) and ran it without any problem.

**Comment by Maryom** [comment]
@ranesr Are you using Xcode 8 and Swift 3 ?

**Comment by ranesr** [comment]
@Maryom I am using Xcode 8.2.1(8C1002) and Swift 3.0.2

**Comment by Maryom** [comment]
@ranesr Well I don't know why I'm still getting this error :/

**Comment by anto004** [comment]
For those who came across the same problem
Put the above code in 
```
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure();
        GIDSignIn.sharedInstance().clientID = FirebaseApp.app()?.options.clientID
        return true
    }
```
