### ISSUE TITLE
Android: starter code does not include imageUrl in FriendlyMessage

### ISSUE THREAD

**Issue by danielle-h** [firebase/friendlychat#160]
android-start does not include imageUrl in FriendlyMessage, the ImageView in item_message.xml, the ImageView in the View Holder, and all the functions pertaining to them. I found them in the full code of the android app.

**Comment by drdavidpier** [comment]
In addition the mainactivity file and the tutorial is missing any reference to `messageImageView = (ImageView) itemView.findViewById(R.id.messageImageView);` which is present in the complete code

**Comment by kroikie** [comment]
This has been fixed, thanks for catching this!
