### ISSUE TITLE
Section 8: Improper call of FriendlyMessage.class

### ISSUE THREAD

**Issue by salimshivani** [firebase/friendlychat#163]
The FriendlyMessage.java in MainActivity.java is not called properly in android-start. The constructor overrides 3 arguments in FriendlyMessage.java whereas in MainActivity.java 4 arguments are passed.

Also, in putImageInStorage() , task.getResult().getMetadata() show an error "This method should only be accessed from tests or within private scope.

P.S.: The FirebaseAnalytics is used in section 12, while it is initialized in section 13.

**Comment by anudeep3998** [comment]
Isn't it the other way round? FriendlyMessage expects 4 String parameters , while MainActivity's send button listener only passes only 3 arguments.

**Comment by kroikie** [comment]
The FriendlyMessage usage has been updated, Analytics has been removed from section 12. Thanks for catching that.
