### ISSUE TITLE
Image sending is not working

### ISSUE THREAD

**Issue by prafulSingh** [firebase/friendlychat#166]
Image sending is not working because  `REQUEST_IMAGE ` constant is not at all defined anywhere , and according to the code provided in tutorial we have something like `startActivityForResult(intent, REQUEST_IMAGE);` , (under section  8 send messages inside `mAddMessageImageView.setOnClickListener`)

**Comment by RNT17** [comment]
The Android codelab was updated, but the code into github wasn't.

**Comment by kroikie** [comment]
This has been resolved thanks, @prafulSingh
