### ISSUE TITLE
typo in Step #9 of web-start tutorial

### ISSUE THREAD

**Issue by TongWR** [firebase/friendlychat#168]
In `FriendlyChat.prototype.saveImageMessage` function, `this.messageRef` is misspelled as `this.messagesRef` causing error.

Contributing guideline says

> Create your patch, **including appropriate test cases.**

I don't seem to find any test. Do I need one in order to submit a PR?

Thanks!

**Comment by nicolasgarnier** [comment]
Hey @TongWR,

I double checked but `this.messagesRef` is definitely correct. Could you tell me what was the error caused?

Cheers

**Comment by TongWR** [comment]
Ah you're right. It's I checked my code, it's actually a typo _I_ made earlier that caused error on my machine. This is embarrassing. Thanks a lot!
