### ISSUE TITLE
Version mismatch: Initialization snippet from firebase console and npm use different firebase versions

### ISSUE THREAD

**Issue by willramsey** [firebase/friendlychat#169]
Running npm install -g firebase-tools currently installs version 3.4.0 by default while version 3.7.0 is loaded in the script tag.

FIX: 
1. Type firebase version in the terminal. Output is e.g. 3.4.0
2. Ensure script element loads this same version
  Change the snippet src attribute
    FROM:
    <script src="https://www.gstatic.com/firebasejs/3.7.0/firebase.js"></script>
    TO:
    <script src="https://www.gstatic.com/firebasejs/3.4.0/firebase.js"></script>

**Comment by nicolasgarnier** [comment]
Hey @willramsey ,

Actually these two versions don't really have anything to do with each other :) I know these version numbers are close and that may be a bit confusing  but CLI v 3.4.0 should have no problem with the JS SDK v 3.7.0 being loaded onto your page.

Cheers!
