### ISSUE TITLE
FriendlyMessage Constructor issue.

### ISSUE THREAD

**Issue by balatimuz** [firebase/friendlychat#170]
public FriendlyMessage(String text, String name, String photoUrl) {
having only 3 Arguments but in code somewhere used like below causing errors..

FriendlyMessage tempMessage = new FriendlyMessage(null, mUsername, mPhotoUrl,LOADING_IMAGE_URL);

Some bugs in Task getDownloadURL.
Thank You.

**Comment by RNT17** [comment]
You can create a new Constructor.
Something like this: public FriendlyMessage(String text, String name, String photoUrl, String imageUrl) { }
[See here](https://github.com/firebase/friendlychat/commit/d7addad8bbb17b9a50f6f67828887dfd74475b0b#diff-bde92ace3dabf2f9d9233fee4fc7803f)

**Comment by kroikie** [comment]
This has been resolved thanks for catching it @balatimuz
