### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by rahul-thakoor** [firebase/friendlychat#171]
https://codelabs.developers.google.com/codelabs/firebase-web/#6

> In your project in Firebase console visit the Database section on the left navigation bar. On this page you will see the data that is stored in your Firebase **Relatime** Database.

Should be 

> In your project in Firebase console visit the Database section on the left navigation bar. On this page you will see the data that is stored in your Firebase **_Realtime_** Database.

**Comment by kroikie** [comment]
fixed thanks @rahul-thakoor
