### ISSUE TITLE
Cannot resolve symbols from Synchronize messages

### ISSUE THREAD

**Issue by IoanDamian** [firebase/friendlychat#172]
When replacing mProgressBar.setVisibility(ProgressBar.INVISIBLE); to synchronize messages , Android logs that he cannot resolve Uri, getResult, isSuccesfull, getException
![capture](https://cloud.githubusercontent.com/assets/15225918/23825884/0d2ce088-069b-11e7-9d39-a1651be088ba.PNG)

**Comment by kroikie** [comment]
Added, thanks @IoanDamian
