### ISSUE TITLE
npm and nodejs prereq missing in codelab Overiew page

### ISSUE THREAD

**Issue by sowmyakann** [firebase/friendlychat#173]
https://codelabs.developers.google.com/codelabs/firebase-web/#3
This page says: 
To install the CLI you need to have installed npm which typically comes with NodeJS.

This should be mentioned as a prereq in the What you'll need section on the Overview page.
https://codelabs.developers.google.com/codelabs/firebase-web/#0

Otherwise, the learner has to spend several minutes updating XCode and installing nodejs in the middle of the codelab.

**Comment by kroikie** [comment]
Good call, added.
