### ISSUE TITLE
Step 8 : FriendlyMessage class has 4 arguments

### ISSUE THREAD

**Issue by rawatshailender** [firebase/friendlychat#179]
FriendlyMesssage constructor has 4 arguments rather than 3 as mentioned in Step 8 (Send Messages) 
```
 FriendlyMessage(mMessageEditText.getText().toString(),
                               mUsername,
                               mPhotoUrl);
```

**Comment by conorleeds** [comment]
I think the last argument should be LOADING_IMAGE_URL
that is what is used in the onActivityResult method

**Comment by RNT17** [comment]
Add in your FriendlyMessage Class a new constructor. This will suport the new variable _imageUrl_. 

```
 public FriendlyMessage(String text, String name, String photoUrl, String imageUrl) {
        this.text = text;
        this.name = name;
        this.photoUrl = photoUrl;
        this.imageUrl = imageUrl;
    }
```

**Comment by kroikie** [comment]
Updated to use the correct constructor, thanks for catching this.
