### ISSUE TITLE
Typo in Step 11 of Codelabs tut

### ISSUE THREAD

**Issue by niiapa** [firebase/friendlychat#18]
```
// Sets the URL of the given img element with the URL of the image stored in Firebase Storage.
FriendlyChat.prototype.setImageUrl = function(imageUri, imgElement) {
  // If the image is a Firebase Storage URI we fetch the URL.
  if (imageUri.startsWith('gs://')) {
    imgElement.src = FriendlyChat.LOADING_IMAGE; // Display a loading image first.
    this.storage.refFromURL(imageStorageUri).getMetadata().then(function(metadata) {
      imgElement.src = metadata.downloadURLs[0];
    });
  } else {
    imgElement.src = imageUri;
  }
};
```

The line `this.storage.refFromURL(imageStorageUri).getMetadata().then(function(metadata) {`
should have imageUri in parenthesis instead of imageStorageUri.

Secondly, and unrelated to the title, image upload doesn't seem to work for my and my friend. We've tried everything.

**Comment by nicolasgarnier** [comment]
Hey @niiapa we fixed this about 2 hours ago. Can you refresh your page and check that you see the fix? Let me know if you still see the issue.

Thanks for reporting this!
