### ISSUE TITLE
firebase-cloud-functions - using web gives notification 2 times.

### ISSUE THREAD

**Issue by rahulmittal** [firebase/friendlychat#180]
URL : https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#9

when we post the message on friendly chat (https://friendlychat-5b486.firebaseapp.com/) and navigates to different tab we get notification 2 times..  While we are on the same tab - get it once..

![capture-20170322-190534](https://cloud.githubusercontent.com/assets/4521131/24200268/9f4ec8b0-0f32-11e7-964d-ba621c3dbdf2.png)

**Comment by kroikie** [comment]
From looking at the domains that the notifications are coming from. It looks like you have a local app (localhost:5000) running that may also be receiving the notification. Be sure to stop your local app and you should be down to a single notification per message.
