### ISSUE TITLE
Firebase Android Codelab step 11

### ISSUE THREAD

**Issue by RNT17** [firebase/friendlychat#182]
Method applyRetrievedLengthLimit() Does not initialize the EditText mMessageEditText causing crash.
Please add: `mMessageEditText = (EditText) findViewById (R.id.messageEditText);`

```
public void applyRetrievedLengthLimit(){
        Long friendly_msg_length = mFirebaseRemoteConfig.getLong("friendly_msg_length");
        // add
        mMessageEditText = (EditText) findViewById(R.id.messageEditText);
        mMessageEditText.setFilters(new InputFilter[]{
                new InputFilter.LengthFilter(friendly_msg_length.intValue())
        });
        Log.d(TAG, "FML is: " + friendly_msg_length);
    }
```

**Comment by kroikie** [comment]
mMessageEditText is initialized in [onCreate](https://github.com/firebase/friendlychat/blob/master/android-start/app/src/main/java/com/google/firebase/codelab/friendlychat/MainActivity.java#L139). You should not need to initialize it in applyRetrievedLengthLimit.

**Comment by RNT17** [comment]
thanks @kroikie. I was using fetchConfig before be initialized mMessageEditText.
