### ISSUE TITLE
Step 10 - Show Notifications

### ISSUE THREAD

**Issue by EvergreenGOD** [firebase/friendlychat#183]
Could someone tell me what we have to do to send the HTTP request?
I don't know where I should write it..

**Comment by nicolasgarnier** [comment]
Hey @EvergreenGOD just below the HTTP request there is this:

`You can do this by using cURL in a command line:` and then we show you how to send the request using cURL.

**Comment by EvergreenGOD** [comment]
Is cURL the consol with one we start the firebase server?

**Comment by nicolasgarnier** [comment]
Here is the cURL website: https://curl.haxx.se/

Yes it is a command line tool just like the Firebase CLI.
