### ISSUE TITLE
Typo in Codelabs guide

### ISSUE THREAD

**Issue by sweetIan** [firebase/friendlychat#19]
https://codelabs.developers.google.com/codelabs/firebase-web/index.html#10

In section
**Display images from Firebase Storage**

```
    imgElement.src = FriendlyChat.LOADING_IMAGE; // Display a loading image first.
```
should be
```
    imgElement.src = FriendlyChat.LOADING_IMAGE_URL; // Display a loading image first.
```

**Comment by nicolasgarnier** [comment]
Thanks so much for filing this @sweetIan. I've fixed it and now need to wait for the instructions to be published again.
