### ISSUE TITLE
Firebase Web codelab - Step 12. Storage Security Rules [Optional]

### ISSUE THREAD

**Issue by dawogfather** [firebase/friendlychat#199]
![image](https://cloud.githubusercontent.com/assets/447826/24985593/8d0e66e4-2038-11e7-87f1-50c394c55cd5.png)

The sentence highlighted in the screen shot (and included below) doesn't seem to make sense as the example following it doesn't have a PROJECT_ID in it. 

> Update the rules to the following which only allows users to write to their own folder (don't forget to replace the <PROJECT_ID> placeholder with your Firebase project ID):

**Comment by kroikie** [comment]
Thanks for noting this @dawogfather, updated.
