### ISSUE TITLE
User Sign-in

### ISSUE THREAD

**Issue by uzusan** [firebase/friendlychat#2]
In the Initialize Firebase Auth section, the Firebase SDK features, this.auth(); etc return an error saying this.auth() is not a function:
```
  // Shortcuts to Firebase SDK features.
  this.auth = this.auth();
  this.database = this.database();
  this.storage = this.storage();
```

> main.js:59 Uncaught TypeError: this.auth is not a function

Changing these to firebase or more explicitly window.firebase solves this:
```
  // Shortcuts to Firebase SDK features.
  this.auth = firebase.auth();
  this.database = firebase.database();
  this.storage = firebase.storage();
```

**Comment by nicolasgarnier** [comment]
Fixed!
