### ISSUE TITLE
uploaded images not displayed

### ISSUE THREAD

**Issue by pmuston** [firebase/friendlychat#20]
not sure if this is the correct way to provide this feedback...
but when following instruction from:
https://codelabs.developers.google.com/codelabs/firebase-web/index.html
Section 11 and following along editing web-start project.

setImageUrl snippet fails to create correct URL.
in console getting:
firebase.js:362 Uncaught ReferenceError: imageStorageUri is not defined

reference to imageStorageUri should be imageUri

code is correct in completed web project here

**Comment by nicolasgarnier** [comment]
Thanks for the report. We had indeed this issue in the codelab which we fixed yesterday. It seems your browser still had the older version of the codelab with the issue in its cache.
Sorry about that!
