### ISSUE TITLE
Firebase Android Codelab #7 Read Messages Missing info / OnCompleteListener Error

### ISSUE THREAD

**Issue by gitblair** [firebase/friendlychat#201]
I suppose it could just be my issue but just in case:

As followed you end up with an error with

```
new OnCompleteListener<Uri>() {
           @Override
           public void onComplete(@NonNull Task<Uri> task)
```

In order for me to get this working, I had to add the following to the top import section of MainActivity.java:

```
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
```

**Comment by kroikie** [comment]
@gitblair Thanks for pointing that out, fixed.
