### ISSUE TITLE
doc: link points to google internal page

### ISSUE THREAD

**Issue by adegreiff** [firebase/friendlychat#204]
the link to the pricing page in step 10 of the docs https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/index.html?index=..%2F..%2Findex#9

points to 

https://firebase-dot-devsite.googleplex.com/pricing/

which does not seem to be the official site.

**Comment by pbusswood** [comment]
+1, noticed the same issue

**Comment by kroikie** [comment]
Thanks for the heads up @adegreiff and @pbusswood, updated.
