### ISSUE TITLE
No FCM

### ISSUE THREAD

**Issue by ishwardhanuka** [firebase/friendlychat#21]
https://firebase.google.com/docs/samples/

mentions friendlychat is supposed to have FCM.

**Comment by nicolasgarnier** [comment]
Unfortunately FCM is only available to Android and iOS today (which they do have as part of this codelab).

**Comment by ishwardhanuka** [comment]
Hey @nicolasgarnier I dont see any code relating to FCM. Could you please point me to the file?

**Comment by nicolasgarnier** [comment]
Sure! You'll find that in [step 9 of the Android codelab](https://codelabs.developers.google.com/codelabs/firebase-android/#8) for instance. However I can;t seem to find such code on the iOS codelab. @iulukaya are there plans to add FCM to the iOS codelab?

**Comment by iulukaya** [comment]
FCM requires APNs to be setup, and registered to Apple. So we took it out from the codelab, but you can always look into the samples.
https://github.com/firebase/quickstart-ios/tree/master/messaging
