### ISSUE TITLE
Doc: storage.rules is referred to as a JSON file

### ISSUE THREAD

**Issue by mieky** [firebase/friendlychat#210]
In "[Storage Security Rules (optional)](https://codelabs.developers.google.com/codelabs/firebase-web/#11)", storage.rules is referred to as a JSON file:

> In your firebase.json file, add a storage.rules attribute pointing to a JSON file containing the rules shown above:

Which would be better without the word "JSON" removed, as that's not the case.

**Comment by kroikie** [comment]
Thanks @mieky, updated.
