### ISSUE TITLE
 Install Firebase command line tools step 1 may be incorrect.

### ISSUE THREAD

**Issue by mikeonline** [firebase/friendlychat#22]
when following the instructions here: https://console.firebase.google.com/project/friendlychat-740b9/hosting

on step 1: Install Firebase tools
it says to install using the command: "npm install -g firebase-tools"

yet on this page: https://codelabs.developers.google.com/codelabs/firebase-web/#4
it says after installing, check the version using:  "firebase version" and that the version should be "3..."
However it reports version 2.2.

using the instructions here: https://www.npmjs.com/package/firebase-cli
by running the commands:
npm install firebase-cli
and then
npm install -g firebase-tools

it reports version 3.0.

**Comment by nicolasgarnier** [comment]
@mikeonline did you ever installed the Firebase tools/cli before on your machine (before we launched v3 at Google IO) basically did you have v2.2 previously installed perhaps?

`firebase-cli` has been deprecated a year ago and only installs v1. NPM should have printed this message"

    npm WARN deprecated firebase-cli@1.2.0: Use firebase-tools instead.

Both v2 and v3 can be installed with `npm install -g firebase-tools` but by default the latest version (3.0.0) gets installed.

**Comment by mikeonline** [comment]
Yes this fixes the issue
thanks
