### ISSUE TITLE
tableView:cellForRow indexPath:" methods typo

### ISSUE THREAD

**Issue by mccomasd** [firebase/friendlychat#221]
On part 6 (activate realtime database) of the firebase tutorial for swift there is a typo
` func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell`

is supposed to be 
` func tableView(_tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell`

The space between `(_tableView: UITableView ` needed to be removed.

**Comment by morganchen12** [comment]
Removing the space results in a compiler error on Swift 3+. What version of Swift are you using?
