### ISSUE TITLE
Is it possible to create sessions of this app for multiple game instances?

### ISSUE THREAD

**Issue by raviprasadmr** [firebase/friendlychat#228]
Is it possible to create sessions of this app for multiple game instances? I am looking to have a chat functionality in a multiplayer game. For different games I need the instance of this chat with members of the game logged in. Is it possible?

**Comment by nicolasgarnier** [comment]
Hey @raviprasadmr as you noticed this app is simplified to allow for a simpler instructional codelab. While it's certainly possible to enhance this chat app for multi-room you should have a look at [Firechat](https://firechat.firebaseapp.com/) which is a fully fledged Chat client using Firebase. It might be what you are looking for.
