### ISSUE TITLE
Setup the Firebase CLI to use your Firebase Project instructions may be wrong.

### ISSUE THREAD

**Issue by mikeonline** [firebase/friendlychat#23]
page: https://codelabs.developers.google.com/codelabs/firebase-web/#4

under step 5 the instruction;
Setup the Firebase CLI to use your Firebase Project:

$~> firebase use --add

returns: 
Error: firebase use must be run from a Firebase project directory.

**Comment by nicolasgarnier** [comment]
Mhh strange. `firebase use --add` should be working as long as you have a `firebase.json` file in your directory.
Perhaps you did not do it from the `web-start` directory but from the root of the repo? I'll add instructions to make sure people enter this repo first.
Thanks for the report.
