### ISSUE TITLE
Undeclared types in Swift Example

### ISSUE THREAD

**Issue by FredvanRijswijk** [firebase/friendlychat#24]
![schermafbeelding 2016-05-20 om 19 29 49](https://cloud.githubusercontent.com/assets/899180/15436304/7da28ce0-1ec1-11e6-823d-54ef194a25a0.png)

After following the steps in codelabs, I get this... Undeclared types...

**Comment by nicolasgarnier** [comment]
@iulukaya can you have a look?

**Comment by iulukaya** [comment]
I just updated the imports from seperate modules to
"import Firebase", please do so in your source files and it should work.

**Comment by FredvanRijswijk** [comment]
Thnx, It's fixing the Undeclared errors, but it won't build... Starting again, new xcode project and got clone etc... gives this error

    1.	While loading members for 'SignInViewController' at <invalid loc>
    2.	While deserializing 'setDisplayName' (FuncDecl #16) 

Clean, restart xcode, clean again and deleted DerivedData and build again... but stil is giving this error
