### ISSUE TITLE
google signin  photo NULL

### ISSUE THREAD

**Issue by abhayworld123** [firebase/friendlychat#27]
google signin JSON returning photoURL NULL value .

**Comment by slotbite** [comment]
Image Api is down same problem...

**Comment by nicolasgarnier** [comment]
Is this with the Android, Web or iOS app ?

**Comment by slotbite** [comment]
web for me

**Comment by nicolasgarnier** [comment]
OK so This issue seems to be related to the profile pic URL.
@abhayworld123 can you share your UID here? Are you sure that you have uploaded a Profile Pic on your Google account?

**Comment by abhayworld123** [comment]
yes with web , and i do have a profile pic .

**Comment by abhayworld123** [comment]
SxkpdGL6gWgYdtMJjnEdnkDet7z1   UID

https://friendlychat-59f2e.firebaseapp.com/

**Comment by holazollil** [comment]
I have same problem. I can't see the picture of  "Sign in with google". How did you solve it?

**Comment by abhayworld123** [comment]
Hi , holazollil  Its now working , there was some issue in google auth and storage bucket .

**Comment by nicolasgarnier** [comment]
We have an issue where Google accounts that have not enabled Google+ would not get a Profile pic and/or full name. This is a bug with Firebase. It should get fixed at our next release (3.2.0). Sorry about this. If this keeps happening after 3.2.0 gets release please feel free to re-open the bug.
