### ISSUE TITLE
Android Start Google Sign In failed.

### ISSUE THREAD

**Issue by slotbite** [firebase/friendlychat#28]
On method **onActivityResult** of mi **MainActivity.java**  show this 
`            } else {
                // Google Sign In failed
                Log.e(TAG, "Google Sign In failed.");`

**Comment by slotbite** [comment]
Well finally login , make a new project, after get the sha1 code in Gradle->Android-start->Tasks->singningReports, put the new google-services.json on src folder and uninstall app ..... Run the project! and voilà , happy coding!

**Comment by nicolasgarnier** [comment]
@kroikie

**Comment by slotbite** [comment]
finally works.. close thx

**Comment by nicolasgarnier** [comment]
👍
