### ISSUE TITLE
Android: Retrieve photoURL not populating from Firebase

### ISSUE THREAD

**Issue by paul-matthews** [firebase/friendlychat#31]
When a record is loaded from Firebase, the photoURL isn't being populated in the model. This is because the photoURL db property doesn't match the Camel Case attribute referenced in the model.

Please change photoUrl to photoURL, setPhotoUrl to setPhotoURL and getPhotoUrl to getPhotoURL.

This is not an issue when a message is sent because the model's constructor is called and sets the right property. I'm not sure if that value is carried through to the DB but the client UI looks correct.

**Comment by kroikie** [comment]
Messages with photoUrls should be populated by the model, thus there should never be a field photoURL coming from the db. Could you expand on where you found photoURL coming from the db?

**Comment by nicolasgarnier** [comment]
Hey @paul-matthews is your bug report for the Web, iOS or Android codelab?

**Comment by paul-matthews** [comment]
@nicolasgarnier it's in the title :D 

@kroikie the name of the model property is wrong, it should be photoURL but is photoUrl. Therefore when Firebase directly sets the property on the class, it's not set.

+ Steps to Reproduce
- Write a message in the web
- Open mobile app look at messages, all of them will have no sender image

P.s. I'm happy to create a PR.

**Comment by kroikie** [comment]
@paul-matthews if you write a message in the web, it should add a field photoUrl to the message object. I'm still not sure where photoURL is being added to the database, could you point to that?

**Comment by kroikie** [comment]
Spoke with @paul-matthews offline, seems there was a bit of an auto-complete issue. So closing.
