### ISSUE TITLE
Syntax error building Swift tutorial

### ISSUE THREAD

**Issue by paulb777** [firebase/friendlychat#36]
Syntax error when first building Swift tutorial https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#2

<img width="1135" alt="screen shot 2016-06-07 at 12 53 22 pm" src="https://cloud.githubusercontent.com/assets/73870/15872667/6c4f7448-2caf-11e6-8cf7-4afb175c69f9.png">

**Comment by iulukaya** [comment]
Looks like we fixed that in full app but not starter. Fixed it, thanks.
https://github.com/firebase/friendlychat/pull/41
