### ISSUE TITLE
Swift Tutorial - Internal Error when clicking Create Account

### ISSUE THREAD

**Issue by paulb777** [firebase/friendlychat#37]
On page 5 of the tutorial, https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#4, I get an Internal Error when clicking "Create Account". 

Here is the tail of the log from the Xcode console:

<FIRAnalytics/DEBUG> Uploading data. Host: https://play.googleapis.com/log
2016-06-07 16:52:47.281 FriendlyChatSwift[90258:] <FIRAnalytics/DEBUG> Received SSL challenge for host. Host: https://play.googleapis.com/log
An internal error has occurred, print and inspect the error details for more information.

**Comment by paulb777** [comment]
Also, it's not clear how to "print and inspect the error details". Turning on the -FIRAnalyticsDebugEnabled option added other logging, but nothing about the error that I could tell.

**Comment by paulb777** [comment]
Workaround seems to be entering an email address with an @ character and a non-zero length password. Then there will be a useful error message in the log or a successful login.

**Comment by iulukaya** [comment]
Yes, @ is needed for emails. This is being checked and fixed at Firebase side, not a sample issue.
