### ISSUE TITLE
firebase serve config

### ISSUE THREAD

**Issue by vladiim** [firebase/friendlychat#4]
Whilst working through you [Web Chat App Javascript tutorial](https://codelabs.developers.google.com/codelabs/firebase-web/#5) I hit an error when executing `firebase serve`.

From, `firebase-debug.log`:
`[debug] TypeError: Cannot read property 'public' of undefined
    at Server.<anonymous> (/usr/local/lib/node_modules/firebase-tools/commands/serve.js:25:15)`

I was able to prevent this error by commenting out the following lines in `serve.js` (obviously not ideal):
`    if (config.public && config.public !== '.') {
      logger.info(chalk.bold('Public Directory:'), config.public);
    }`

**Comment by uzusan** [comment]
I had a similar issue. If you go into the web-start directory and run:
`firebase init`
when you get to this question:
```
=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

? What do you want to use as your public directory?

```
You can use ./ here (make sure you tell it not to redirect links or overwrite index.html as well in the other steps for init).

When you get to step 13:
https://codelabs.developers.google.com/codelabs/firebase-web/#12

firebase.json has a section that does the same thing:
```
"hosting": {
    "public": "./",
```

**Comment by vladiim** [comment]
Thanks @uzusan, I was sure it was a rookie error.

**Comment by nicolasgarnier** [comment]
Thanks for the report guys. I'll fix this. It seems the alpha version of the CLI that I was using did not require the hosting/public attribute to be set but it now does...
