### ISSUE TITLE
Another typo

### ISSUE THREAD

**Issue by stevewitman** [firebase/friendlychat#40]
see ... https://codelabs.developers.google.com/codelabs/firebase-web/#10
should this be
`gs://<bucket>/<uid>/<timestamp>/<file_name>`.
instead of 
`gs://<bucket>/<uid>/<timestamp/<file_name>`.
here ...
> In the chat messages we saved the Firebase Storage reference of the images. These are of the form `gs://<bucket>/<uid>/<timestamp/<file_name>`. To display these images we need to query Firebase Storage for a URL.

**Comment by nicolasgarnier** [comment]
Thanks! Yes there was a typo here. I've fixed it although we need to wait until the instructions gets deployed again.
