### ISSUE TITLE
Swift Tutorial - Remote Config replacement code does not build

### ISSUE THREAD

**Issue by paulb777** [firebase/friendlychat#42]
The replacement code for FCViewController.swift at https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#9 does not build.

A workaround is to use the code from ios/swift/FriendlyChatSwift/FCViewController.swift

**Comment by paulb777** [comment]
Related question at http://stackoverflow.com/questions/37737731/error-in-firebase-ios-codelab-swift

**Comment by iulukaya** [comment]
Looks like updates to the codelab doc weren't published. They are getting published now, so it will be in sync with the code.
