### ISSUE TITLE
Swift Tutorial - Adding An Image Crashes Application

### ISSUE THREAD

**Issue by conradwt** [firebase/friendlychat#48]
When I try add an image on both iPhone/Simulator, the application crashes with the following message:

'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (4), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'

**Comment by jeffrauch** [comment]
+1

**Comment by nicolasgarnier** [comment]
@iulukaya Could you have a look at the ios issues (or re-assign) when you have a chance?

**Comment by iulukaya** [comment]
Fixed this one.
