### ISSUE TITLE
Web Tutorial - Missing Instructions

### ISSUE THREAD

**Issue by conradwt** [firebase/friendlychat#49]
After typing `firebase use --add` at the end of step 5, what should one type because it's not clear from the provided documentation.

**Comment by ryanbilak** [comment]
After that command you select your firebase project that you created in the online console and give it an alias

**Comment by nicolasgarnier** [comment]
`firebase use --add` should bring you in an interactive mode that lets you select a Firebase project. You'll just have to choose the project you created earlier. Let me know if that is not the case.
