### ISSUE TITLE
Web Tutorial - Typo in step 12

### ISSUE THREAD

**Issue by itamaro** [firebase/friendlychat#50]
In step 12 (Storage Security Rules), the last section header is "Deploy Database Security Rules", while it should be "Deploy ***Storage*** Security Rules"

**Comment by Jillee** [comment]
In step 12 I had service 

firebase.storage {
  match /b/<MYPROJECT_ID>.appspot.com/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
And my localhost5000 chat worked.......

Then I replaced it with  service 
firebase.storage {
  match /b/<MYPROJECT_ID>.appspot.com/o {
    match /{userId}/{timestamp}/{fileName} {
      allow write: if request.auth.uid == userId;
      allow read;
    }
  }
}

And my localhost5000 chat didn't work and I waited an hour or more, signed out and signed in, refreshed my browser......

So then i replaced it with


service firebase.storage {
  match /b/project-5224474240715792645.appspot.com/o {
   match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}

And my localhost5000 chat didn't work and I waited an hour or more, signed out and signed in, refreshed my browser......

any ideas what Ive done wrong?

**Comment by Jillee** [comment]
I had the same project number each time i just anonymised the first two instances for this forum and the 
it was

match /b/project-5224474240715792645.appspot.com/o { every time

**Comment by nicolasgarnier** [comment]
Thx! Fixed it, we'll need to wait for the text to re-deploy to see the fix.
