### ISSUE TITLE
could not import json

### ISSUE THREAD

**Issue by bobzhang** [firebase/friendlychat#53]
> In your project in Firebase console visit the Database section on the left navigation bar. In the overflow menu of the Database select Import JSON. 

could not find import button

**Comment by bobzhang** [comment]
![screen shot 2016-06-18 at 2 17 27 pm](https://cloud.githubusercontent.com/assets/747051/16172865/7912a14c-355f-11e6-8d61-258e65146c9c.png)

**Comment by kroikie** [comment]
It is in the overflow menu on the right of your screen, the three vertical dots.
