### ISSUE TITLE
web issue: adding/sending an image not working. not storing any image in my Firebase Storage

### ISSUE THREAD

**Issue by hangal2001** [firebase/friendlychat#54]

**Comment by nicolasgarnier** [comment]
@hangal2001 Could you tell us:
- Is this for the Web, Android or iOS codelab?
- At which step of the codelab you are trying this?
- Have you tried the finished code in /android, /ios or /web ?
- Any error messages in the console?

**Comment by hangal2001** [comment]
this issue was for the Web. today, Image message worked nicely. Sorry for inconvenience. Issue were with me. Closing this issue.

**Comment by icreatevisions** [comment]
Do you remember what your issue was and how you fixed it?
