### ISSUE TITLE
5. Install the Firebase Command Line Interface

### ISSUE THREAD

**Issue by two9seven** [firebase/friendlychat#58]
Step five of the tutorial is somewhat misleading. Even-though the instructions only state to install the CLI, the hosting walk through led me to deploy, which messed up the next steps in the tutorial for deploying the web-start app. I would just clarify what the purpose is of the CLI and not to deploy right away. 

D

**Comment by Lorenzoygata** [comment]
ss

**Comment by katogo** [comment]
which kind of OS are you using coz if ur using windows neglect the $ and the (- )sign

**Comment by nicolasgarnier** [comment]
We're now asking developers to simply run `npm install -g firebase-tools`
