### ISSUE TITLE
#func sendMessage(data: [String: String]) { - a value is returning nil 

### ISSUE THREAD

**Issue by ziosmobile** [firebase/friendlychat#59]
`func sendMessage(data: [String: String]) {
    var mdata = data
    mdata[Constants.MessageFields.name] = AppState.sharedInstance.displayName'

'AppState.sharedInstance.displayName' is returning 'nil' and App is craching. no error handle.

Please change it with '**FIRAuth.auth()?.currentUser?.displayName**'

**Comment by iulukaya** [comment]
Thanks.
