### ISSUE TITLE
Update web tutorial to include firebase init

### ISSUE THREAD

**Issue by cbetz** [firebase/friendlychat#6]
There is a missing step in "5. Install the Firebase Command Line Interface." One must `firebase init` and enter "." for the public directory. Please update the tutorial.

Without doing this `firebase serve` will fail as it is looking for "public." See #4

**Comment by nicolasgarnier** [comment]
Thanks for trying out our codelabs @cbetz!
Your issue might be because you are using an older version of the CLI. Rune `firebase version` to make sure it prints out `3.0.0`.

Right now with the new CLI I don't seem to be getting an error when trying `firebase serve`...

**Comment by nicolasgarnier** [comment]
Actually never mind. It seems the alpha version of the CLI I was using did not require the "hosting/public" attribute in the firebase.json but it now does...

**Comment by nicolasgarnier** [comment]
Fixed thanks! We'll need to wait a bit for the codelab script to be pushed (so that it makes sense with the code in the repo) I've added the hosting attribute in the `firebase.json` file that you start with.

**Comment by cbetz** [comment]
Thank you for the quick reply @nicolasgarnier
