### ISSUE TITLE
Buggy/intermittent scrolling on the x-axis of code samples on Chrome on Android

### ISSUE THREAD

**Issue by mrkiffie** [firebase/friendlychat#61]
Browser: Chrome 
Browser version: 50.0.2661.89
Operating system: Android
Operating system version: 5.0.2
Device: Samsung SM-A5000F

What steps will reproduce the problem:
1. View step ["7. User Sign-in"](https://codelabs.developers.google.com/codelabs/firebase-web/#6) on Chrome on Android.
2. Scroll down to the code sample so that it is in the upper half of the screen (see figure 1).
3. Attempt to scroll code sample to see the initially obscured code.
4. Note that the scrolling on the X-axis doesn't work (most of the time).
5. Scroll up the page until the code sample is between the navigation arrows (see figure 2).
6. Attempt to scroll code sample to see the initially obscured code by scrolling between the navigation arrows.
7. Note that the scrolling works as expected.

What is the expected result?
- To be able to scroll the code samples to view the entire code sample

What happens instead of that?
- Scrolling on the X-axis is inconsistent. Scrolling only consistently works when the code sample and scrolling are between the navigation arrows.

Please provide any other information below, and attach a screenshot if possible.
- I attempted to debug the issue via the chrome dev tools and found that the issue seemed to disappear as soon as the page was inspected 😞. Refreshing the page while inspecting seemed to be sufficient to reproduce the error.

**Figure 1**
![scrolling intermittently works](https://cloud.githubusercontent.com/assets/2323810/16900890/c6526660-4c32-11e6-9764-e95b7af73afa.png)

**Figure 2**
![scrolling consistently works](https://cloud.githubusercontent.com/assets/2323810/16900889/c649d950-4c32-11e6-9c1f-b8a313accd8a.png)

**Comment by mrkiffie** [comment]
Whoops - Sorry wrong repo :blush: - I've had too much coffee today. 

Could someone point me in the correct direction as to where to log this issue? That would be very appreciated. Thanks. 😃 

Great tutorial BTW!

**Comment by nicolasgarnier** [comment]
Hey @mrkiffie you can post a bug repport here: https://github.com/googlecodelabs/feedback whichbis actively followed by the team who wrote our codelab tool/website
Cheers!
