### ISSUE TITLE
PhotoUploader not working

### ISSUE THREAD

**Issue by santoshdheeraj** [firebase/friendlychat#62]
When tried to test photo upload for the web chat application on web, the photo being uploading is struck in loading position for ever. There's no update if it is uploaded or any error in uploader. All it does is spinning the loading icon

**Comment by nicolasgarnier** [comment]
@santoshdheeraj could you upload your web app so I could see what's wrong? (just run `firebase deploy`)?

**Comment by nicolasgarnier** [comment]
I'll close because no response but if you still need help feel free to comment.
