### ISSUE TITLE
Large amounts of messages will start to overlap on each other in Safari

### ISSUE THREAD

**Issue by alien35** [firebase/friendlychat#65]
If you write, say, 20 messages in the box they'll start to overlap on each other (only in Safari, other browsers are fine). The reason is the class 'message container' doesn't want to properly wrap around the content, hence eventually creating the mess.

**Comment by nicolasgarnier** [comment]
Thanks! I'll look into it.

**Comment by SergeantPeanuts** [comment]
This issue is still not solved. Any ideas how to perfectly wrap around the content so that messages don't begin to over lap?

**Comment by nicolasgarnier** [comment]
Now Fixed! Sorry for the delay!
