### ISSUE TITLE
My app doesn't work on a server

### ISSUE THREAD

**Issue by truetothemark** [firebase/friendlychat#68]
I have created a chat-app with your tutorial. It works just fine on a local host, but it doesn't work after deployment. The app - https://my-chat-26e48.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
It doesn't seem anything was deployed. Could you paste the output from the `firebase deploy` command?

**Comment by truetothemark** [comment]
I've tried to resolve the situation myself and something went wrong )) Yet, I've made a new project and used the code from the "web" folder - it works just fine. So it's my mistake, I'll try to figure out what I did wrong. Thanks for answering in such a short notice.

**Comment by nicolasgarnier** [comment]
I'm glad to hear this. Cheers!
