### ISSUE TITLE
Cannot deploy?

### ISSUE THREAD

**Issue by gg2001** [firebase/friendlychat#7]
I am trying to deploy the completed app, however it is not working. Here are my logs:

> egaumbp:web gg$ firebase deploy
> 
> === Deploying to 'friendlychat-6e4c3'...
> 
> i  deploying database, storage, hosting
> i  storage: checking rules for compilation errors...
> 
> Error: Compilation error in storage.rules:
> 
> [E] 3:12 - Unexpected '<'.
> 
> Having trouble? Try firebase deploy --help

**Comment by yarnball** [comment]
Possibly related to my issue, the sample docs don't give me an actual code for "storageBucket". I put a random value there, and no longer got the error.

**Comment by nicolasgarnier** [comment]
You'll have to replace some placeholder in the storage.rule file. The instructions should be in the README.md file.  Please let me know if the instructions don't make sense!
