### ISSUE TITLE
Property name case mismatch in web app section 11 

### ISSUE THREAD

**Issue by necrobala** [firebase/friendlychat#71]
The case of 'photoURL' property is incorrect in the example code.
https://github.com/firebase/friendlychat/blob/master/web/scripts/main.js#L141.js

This results in profile placeholder image to be shown instead of the user's profile pic

**Comment by nicolasgarnier** [comment]
It seems to actually be correct. Perhaps your user's account simply does not have a profile Pic setup?

**Comment by nicolasgarnier** [comment]
I'll close but feel free to re-open if you still have issues.
