### ISSUE TITLE
firebase serve not working after initializing firebase project

### ISSUE THREAD

**Issue by timothychen01** [firebase/friendlychat#72]
Here's the error I get when I open up `localhost:5000`:

<img width="878" alt="screen shot 2016-08-16 at 11 11 49 am" src="https://cloud.githubusercontent.com/assets/14797288/17704204/52a27e58-63a2-11e6-8c2e-d6e471051218.png">

**Comment by nicolasgarnier** [comment]
Hey @timothychen01 Maybe do a Shift+Reload to force refreshing the page? It does not seem that you are serving the content of the codelab. I'm not sure where this page comes from actually :)

**Comment by kroikie** [comment]
Is this still an issue @timothychen01 ?
