### ISSUE TITLE
Web tutorial step 10 type error

### ISSUE THREAD

**Issue by DanielSank** [firebase/friendlychat#75]
I complete the code changes from step 10 of the web tutorial [1]. I copy/pasted the code from the web tutorial, and then diffed `web-start/main.js` against `web/main.js` to make sure I haven't typed anything wrong. I run the server and try to send a message. When I click the send button, nothing happens, but the browser console logs the following message:

`main.js:77 Uncaught TypeError: Cannot read property 'push' of undefined`

[1] https://codelabs.developers.google.com/codelabs/firebase-web/#9

**Comment by nicolasgarnier** [comment]
Hey @DanielSank I your case `this.messagesRef` seems to be undefined. In theory it should be set by the `loadMessages` function from step 8:

```javascript
// Loads chat messages history and listens for upcoming ones.
FriendlyChat.prototype.loadMessages = function() {
  // Reference to the /messages/ database path.
  this.messagesRef = this.database.ref('messages');
```

`loadMessages` should be called when the user signs in:

```javascript
FriendlyChat.prototype.onAuthStateChanged = function(user) {
  if (user) { // User is signed in!
    ...
    // We load currently existing chant messages.
    this.loadMessages();
  } else { // User is signed out!
  ...
```

Could you check everything is in place? Is our user signed-in?

Thanks!

**Comment by DanielSank** [comment]
Oh brother. I somehow completely skipped step 8, and while I grepped `messagesRef` in my development file, I never did it in `web/secipts/main.js` so I didn't understand where `messagesRef` was supposed to come from.

Works now. Sorry to waste your time.

**Comment by nicolasgarnier** [comment]
No worries! I'm glad you figured it out :)
