### ISSUE TITLE
Database wont sync after importing (web)

### ISSUE THREAD

**Issue by JeffreyCheng92** [firebase/friendlychat#79]
After importing the `initial_messages.json` through the firebase console in the browser and adding the relevant code to `main.js` below:
```
// Loads chat messages history and listens for upcoming ones.
FriendlyChat.prototype.loadMessages = function() {
  // Reference to the /messages/ database path.
  this.messagesRef = this.database.ref('messages');
  // Make sure we remove all previous listeners.
  this.messagesRef.off();

  // Loads the last 12 messages and listen for new ones.
  var setMessage = function(data) {
    debugger // NOTE THE DEBUGGER HERE TO FREEZE PAGE IN CHROME DEV TOOLS
    var val = data.val();
    this.displayMessage(data.key, val.name, val.text, val.photoUrl, val.imageUrl);
  }.bind(this);
  this.messagesRef.limitToLast(12).on('child_added', setMessage);
  this.messagesRef.limitToLast(12).on('child_changed', setMessage);
};
```

the `setMessage` function is never called which means that the sample application is most likely not connected to the database online. 

```
var config = {
    apiKey: "asdfasdfasdfasdfasdf",
    authDomain: "testapp-ed989.firebaseapp.com",
    databaseURL: "https://testapp-ed989.firebaseio.com", // I've checked this url is the same
    storageBucket: "testapp-ed989.appspot.com",
  };
  firebase.initializeApp(config);
```

I've initialized firebase in the bottom of my `index.html` within a `<script>` and in the database tab of my console, the url is `https://testapp-ed989.firebaseio.com/` which is the same as in my config. 

The only thing that I'm not sure about is the database configurations which I dont think does anything different about connecting to the database as long as I'm logged in.

```
{
  "rules": {
    "users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
    }
  }
}
```

![image](https://cloud.githubusercontent.com/assets/12540391/17937555/5f4a152c-69d7-11e6-915d-360ea27521ad.png)

The imported messages wont display regardless of how many times I reload/re-serve/deploy.

**Comment by nicolasgarnier** [comment]
Hey @JeffreyCheng92,

Could you check your browser's Javascript console for any errors? Also could you upload your code online (using `firebase deploy`) and give us the URL?

Thanks!

**Comment by JeffreyCheng92** [comment]
@nicolasgarnier I figured it out. There were no errors but it had to do with the `database.rules.json`. Basically, it wasn't throwing an error when I tried to connect to the `/messages` even if there wasn't any permissions for it. Maybe it can be added to the tutorial? Now my `database.rules.json` looks like (copied from the completed web project): 

```
{
  "rules": {
    "messages": {
      ".read": "auth != null",
      ".write": "auth != null"
    }
  }
}
```

**Comment by JeffreyCheng92** [comment]
Upon further reading, it was actually step 9 where the `database.rules.json` is edited. Maybe step 9 and 8 can be swapped?

**Comment by nicolasgarnier** [comment]
It's very strange because by default, on new projects, the Database rules are:

```json
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

Which should work for the code. Step 9 is actually an optional step for that reason (the app would still work the same if you skipped it). For example could you try to revert the rules to the rules above? Things should still work.

**Comment by JeffreyCheng92** [comment]
Okay I see the issue here now. It wasn't the tutorials fault at all but when I went to import the `initial_messages.json` it said the rules had to be changed before the database could be used.

![image](https://cloud.githubusercontent.com/assets/12540391/17946711/52ff3f0a-69fe-11e6-931e-fc11ce8a6f00.png)

which led me to copy this in my `database.rules.json` as well as in the online rules.

![image](https://cloud.githubusercontent.com/assets/12540391/17946828/d04c1a6e-69fe-11e6-9d0c-9662f603bdc6.png)

Thanks for clearing all of this up!
