### ISSUE TITLE
No sign-in button & Docs update (storageBucket)- "Not enabled Firebase Storage"

### ISSUE THREAD

**Issue by yarnball** [firebase/friendlychat#8]
Hi,

I'm following the docs precisely (https://codelabs.developers.google.com/codelabs/firebase-web/#) but I keep arriving at the error:

I am not able to see a "Sign-in" button (despite it being in the HTML).

Here is the parts I added to `main.js` in case there were any errors there (seeing as parts of the document snippets of code ended in `...` somewhat confusing...):

```
FriendlyChat.prototype.initFirebase = function() {
  // Shortcuts to Firebase SDK features.
  this.auth = firebase.auth();
  this.database = firebase.database();
  this.storage = firebase.storage();
  // Initiates Firebase auth and listen to auth state changes.
  this.auth.onAuthStateChanged(this.onAuthStateChanged.bind(this));
};

FriendlyChat.prototype.signIn = function() {
  // Sign in Firebase using popup auth and Google as the identity provider.
  var provider = new firebase.auth.GoogleAuthProvider();
  this.auth.signInWithPopup(provider);
};

FriendlyChat.prototype.signOut = function() {
  // Sign out of Firebase.
  this.auth.signOut();
};

FriendlyChat.prototype.onAuthStateChanged = function(user) {
  if (user) { // User is signed in!
    // Get profile pic and user's name from the Firebase user object.
    var profilePicUrl = user.photoURL;
    var userName = user.displayName;
  }};

  FriendlyChat.prototype.checkSignedInWithMessage = function() {
  // Return true if the user is signed in Firebase
  if (this.auth.currentUser) {
    return true;
  }};]
```

SEPERATE ISSUE/NOTE:

Initially I kept getting the error:

`You have not enabled Firebase Storage prior to importing the firebase SDK`

I looked at my script, and it seems there is no value for "storageBucket"

**The FIX** If I go to the firebase console>Auth>Web Setup (at the top), it generates a snippet of code which includes a storageBucket.

This storageBucket code was only generated once I enabled a sign-in method on Auth.

You should update the docs to this affect.

**Comment by nicolasgarnier** [comment]
Thanks for repporting. Actually the storage bucket should always be there the first time you generate copy the snippet so this seems like a bug. I'll report this to the Firebase storage team so that they improve the auto-provisioning. Sorry about this!

**Comment by yarnball** [comment]
No problem. Please update regarding the sign-up button.

The notes were a little confusing at **5** (Install the Firebase Command Line Interface). Do I just "install" (`npm install -g firebase-tools`) or do I need to "deploy" also?

Both ways still have the no-sign up button issue. And yes I've enabled Google in the Auth section of the console.

**Comment by nicolasgarnier** [comment]
AH yes that's because you deleted what was inside of `FriendlyChat.prototype.onAuthStateChanged` whereas you should only add the 2 lines at the top of the existing code (just replace the TODO). I'll try to make this clearer in the instructions thanks!

**Comment by nicolasgarnier** [comment]
And for firebase tools you don't need to run `firebase init`. I'll also add something in the instructions about this...

**Comment by nicolasgarnier** [comment]
Also the same applies to `checkSignedInWithMessage` you should just add the lines and replace the `TODO`.

**Comment by nicolasgarnier** [comment]
I changed the error message (for that storageBucket bug) and updated the text in the codelab to make it clearer that you need to add and not replace the function in some cases. Thanks for the report!

**Comment by nicolasgarnier** [comment]
hey @yarnball could you give us your Project ID? We'd like to see what happen in our backend that caused you not to have the `storageBucket` created properly.
