### ISSUE TITLE
Cant run the project.

### ISSUE THREAD

**Issue by terrancelaw93** [firebase/friendlychat#84]
After i run the projects, it will show this comment. How to solve this problem?

Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\user\Desktop\friendlychat-master\android\app\src\debug\google-services.json
  C:\Users\user\Desktop\friendlychat-master\android\app\google-services.json

**Comment by kroikie** [comment]
The error is indicating that you are missing the required google-services.json file. When you create a Firebase project and add your Android app to it you will be able to download the corresponding google-services.json file. You should place it in your app directory then try to build the project again.

See the [Android Setup](https://firebase.google.com/docs/android/setup)
