### ISSUE TITLE
StorageBucket attribute is always empty when adding firebase to webApp

### ISSUE THREAD

**Issue by wadjay3** [firebase/friendlychat#86]
Hello, I am following the steps given on page (using google chrome)
https://codelabs.developers.google.com/codelabs/firebase-web/#3

It says: You've hit a bug. Sorry about that! Close and re-open this dialog and your storageBucket should now be populated.
I have tried this many a times, but doesn't populate the atrribute. The result is I am not able to work with images.
When I browse the project in Firebase console and go to Storage, it gives error: Can't connect to server. Try again in a few minutes. RETRY

What is the solution?

**Comment by mcdonamp** [comment]
Would you mind filing an issue on our [support queue](https://firebase.google.com/support/contact/troubleshooting/)? This sounds like you're falling into an edge case of Storage and we'd like to offer some more personal support.
