### ISSUE TITLE
Step 5 Spelling Mistake

### ISSUE THREAD

**Issue by lclghst** [firebase/friendlychat#89]
> Make sure the Firebase version is 3.x.x. If **you** this reads 2.x.x you still have an older firebase CLI version installed and you may need to fix your PATH.

Spelling mistake above. The bolded **you** should be removed. This is on the [codelabs](https://codelabs.developers.google.com/codelabs/firebase-web/#4) docs.

**Comment by nicolasgarnier** [comment]
Thanks @lclghst ! I fixed it. Now waiting for the codelab text to be re-deployed.

Cheers!
