### ISSUE TITLE
Downloading image uses wrong variable name

### ISSUE THREAD

**Issue by tophcito** [firebase/friendlychat#9]
I've found that when pulling an uploaded image from storage, `main.js`' `setImageUrl()` uses `imageStorageUri` instead of `imageUri`. This results in an undefined error for me. This line works though:
`this.storage.refFromURL(imageUri).getMetadata().then(function(metadata) {`

**Comment by mig82** [comment]
Hi. I just ran into the same issue. It's not hard to tell by reading the code that this variable is not declared. But it would be nicer for the code to be right from the start.

**Comment by ziedhajsalah** [comment]
Same case for me.

**Comment by nicolasgarnier** [comment]
Sorry about that and thanks for the report! I've fixed it now and the fix will be published very soon.
