### ISSUE TITLE
Web tutorial #7

### ISSUE THREAD

**Issue by jouanvela** [firebase/friendlychat#91]
**the profile pic and name of the user not display, since**

in `FriendlyChat.prototype.onAuthStateChanged = function(user) {}`

 `userName` is already used by 
`function FriendlyChat() {
   this.userName = document.getElementById('user-name');
}`

```
    var userName = user.displayName
    this.userPic.style.backgroundImage = 'url(' + profilePicUrl + ')';
    this.userName.textContent = userName;
```

**Comment by nicolasgarnier** [comment]
hey @jouanvela `userName` and `this.userName` are different variables and do not collide. probably the issue comes somewhere else? Let me know if you still need help.
