### ISSUE TITLE
firebase use --add issue

### ISSUE THREAD

**Issue by bruce366** [firebase/friendlychat#92]
Running this in Win 10 Powershell

firebase login .. ok

firebase use --add
? Which project do you want to add? (use arrow keys)

There is no project to select, arrow keys don't work, nothing works.

What is happening please?

**Comment by abehaskins** [comment]
This isn't an issue specific to this repo, try asking on StackOverflow!

**Comment by steven-mercatante** [comment]
Make sure you're logged in as the same account in both the CLI tool and the Firebase web console.
