### ISSUE TITLE
Web: Users not experienced with the terminal get confused about prompt

### ISSUE THREAD

**Issue by momander** [firebase/friendlychat#97]
I was recently a troubleshooting assistant at a session using this codelab. Several users who were not experienced in using a terminal window ended up pasting the entire terminal strings in:

`$~> npm -g install firebase-tools`

They pasted in the "$~>" as well as the command, which means it didn't work. I propose removing the "$~>" terminal prompts from the codelab doc, so users won't have to apply judgment about what to paste in and what not to.

**Comment by nicolasgarnier** [comment]
Fixed!
