### ISSUE TITLE
Web: At end of step 5, tell users which directory to configure

### ISSUE THREAD

**Issue by momander** [firebase/friendlychat#98]
At the end of step 5, the doc tells the user to run

`$~> firebase use --add`

and then to "select your Project ID and follow the instructions". The tool will ask

`What alias do you want to use for this project? (e.g. staging)`

which confuses some users, as they don't know what to enter and there is no guidance in the doc. I propose including an instruction telling users to enter "." (current directory) at this prompt.

**Comment by nicolasgarnier** [comment]
Fixed :) added a  suggestion for this
